### PR TITLE
boilerplate for backend and database

### PR DESCRIPTION
**Pull request by namhai923**

### CODE REVIEW

**Review by LimitlessJesse — APPROVED** [review]
Looks good

**Comment by LimitlessJesse** [comment]
One small thing though, should we call this folder `back-end` or `server`? When we create the folder for UI we should call it `front-end` / `client` to match it. I am just not sure which one is the better terms `back-end` `front-end` or `client` `server`?

**Comment by afazmunshi49** [comment]
> One small thing though, should we call this folder `back-end` or `server`? When we create the folder for UI we should call it `front-end` / `client` to match it. I am just not sure which one is the better terms `back-end` `front-end` or `client` `server`?

I think calling it front-end and back-end should be fine since it is an abstract term. Although I have seen sample projects using both front-end-back-end and client-server.

**Review by afazmunshi49 — APPROVED** [review]
Looks good to me.

**Pull request merged**
