### PR TITLE
User/afaz/front end boilerplate

### PR DESCRIPTION
**Pull request by afazmunshi49**

### CODE REVIEW

**Comment by namhai923** [comment]
Should we remove those License and README files ?

**Comment by afazmunshi49** [comment]
> Should we remove those License and README files ?

I was thinking of removing later (in the next push). This readme contains some valuable information on how to use the template. Besides, there are a lot of useless files that we'll have to clean anyway.

**Comment by namhai923** [comment]
sounds good

**Review by namhai923 — APPROVED** [review]
lgtm

**Review by mike91827 — APPROVED** [review]

**Pull request merged**
