### PR TITLE
added UI for transfer money

### PR DESCRIPTION
**Pull request by mike91827**
https://github.com/namhai923/Bison-Bank-of-Canada/issues/86

### CODE REVIEW

**Comment by afazmunshi49** [comment]
Wondering if the Transfer money should have its own folder instead of putting it in Authentication? E.g. views/pages/TransferMoney"

**Comment by mike91827** [comment]
> 

Yes you are probably right. I will fix that in the next PR

**Comment by mike91827** [comment]
> Wondering if the Transfer money should have its own folder instead of putting it in Authentication? E.g. views/pages/TransferMoney"

Yes you are probably right. I will fix that in the next PR

**Review by afazmunshi49 — APPROVED** [review]
Looks good.

**Pull request merged**
